#!/bin/sh
export SUPERBASH_SOURCE_DIR=~/Documents/projets/superbash/superenv/

. ${SUPERBASH_SOURCE_DIR}/bash_aliases
. ${SUPERBASH_SOURCE_DIR}/bash_functions
. ${SUPERBASH_SOURCE_DIR}/bash_ps1
. ${SUPERBASH_SOURCE_DIR}/git_completion
. ${SUPERBASH_SOURCE_DIR}/git_prompt

test -f ${HOME}/bash_custom && . ${HOME}/bash_custom

