#!/bin/sh

##############
## WRAPPING ##
##############
alias grep="grep -Hn --color=auto"
alias ls="ls -CF --color=auto"
alias la="ls -A"
alias ll="ls -lh"
alias lla="ll -A"
alias du="du -sh"

##############
### MOVING ###
##############

export SUPERBASH_DOCS_PATH=""

PRO=${SUPERBASH_USER_FILES}/projets
export PRO
alias pro="cd ${PRO}"

PROTEX=${SUPERBASH_USER_FILES}/tex
export PROTEX
alias protex="cd ${PROTEX}"

##############
### OTHERS ###
##############
alias freq="cat $HISTFILE | cut -f1 -d' ' | sort | uniq -c | sort -nr | head -n 30"
alias gl="git log --graph --all --color --pretty=format:%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s | less -R"
alias gdb="gdb --quiet"
alias vi="vim"
alias vim="vim -p"
alias tmux="tmux -2" #force 256-color mode
