#!/bin/sh

function mcd(){
	mkdir -p $1
	cd $1
}

function map_vim()
{
	egrep --no-group-separator --color=auto --color=never -B1 "^[a-z]*map" ~/.vimrc | sed -e "s/^\".*$/`printf "\033[1;31m"`& `printf "\033[0;0m"`/g"
}

