#!/bin/sh

##############
## WRAPPING ##
##############
alias grep="grep --color=auto"
alias ls="ls -CF --color=auto"
alias la="ls -A"
alias ll="ls -lh"
alias lla="ll -A"
alias du="du -sh"

##############
### OTHERS ###
##############
alias freq="cat $HISTFILE | cut -f1 -d' ' | sort | uniq -c | sort -nr | head -n 30"
alias gdb="gdb --quiet"
alias vi="vim"
alias vim="vim -p"
alias tmux="tmux -2" #force 256-color mode
