#!/bin/sh
export SUPERBASH_SOURCE_DIR=~/.superbash

if [ -z "${SUPERBASH_USER_FILES}" ] ; then
	SUPERBASH_USER_FILES="$HOME/Documents"
fi

. ${SUPERBASH_SOURCE_DIR}/bash_aliases
. ${SUPERBASH_SOURCE_DIR}/bash_functions
. ${SUPERBASH_SOURCE_DIR}/bash_ps1
. ${SUPERBASH_SOURCE_DIR}/bash_git_completion
test -f ${SUPERBASH_SOURCE_DIR}/bash_custom && . ${SUPERBASH_SOURCE_DIR}/bash_custom

# For i3 support with user-defined terminal
export TERMINAL=gnome-terminal

export PATH=${SUPERBASH_SOURCE_DIR}/../.usr/bin:$PATH
export LD_LIBRARY_PATH=${SUPERBASH_SOURCE_DIR}/../.usr/lib:$LD_LIBRARY_PATH
export INCLUDE_PATH=${SUPERBASH_SOURCE_DIR}/../.usr/include:$INCLUDE_PATH
