#!/bin/sh

##############
## WRAPPING ##
##############
alias grep="grep -Hn --color=auto"
alias ls="ls -CF --color=auto"
alias la="ls -A"
alias ll="ls -lh"
alias lla="ll -A"
alias du="du -sh"

##############
### MOVING ###
##############

export SUPERBASH_DOCS_PATH=""
alias pro="cd ${SUPERBASH_USER_FILES}/projets/"
alias protex="cd ${SUPERBASH_USER_FILES}/tex/"

PRO=${SUPERBASH_USER_FILES}/projets
export PRO
PROTEX=${SUPERBASH_USER_FILES}/tex
export PROTEX

##############
### OTHERS ###
##############
alias freq="cat $HISTFILE | cut -f1 -d' ' | sort | uniq -c | sort -nr | head -n 30"
alias gl="git log --graph --all --color --pretty=format:%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s | less -R"
alias glc="git log | grep Date | awk '{print \" : \"\$4\" \"\$3\" \"\$6}' | uniq -c | sort -t ':'"
